### ISSUE TITLE
dont work on private groups 

### ISSUE THREAD

**Issue by Markowde3jani** [AngelSecurityTeam/CC_Scrapper#4]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\cc_scrapper.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 149, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\requestiter.py", line 87, in __next__
    return self.client.loop.run_until_complete(self.__anext__())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\requestiter.py", line 58, in __anext__
    if await self._init(**self.kwargs):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\messages.py", line 27, in _init
    self.entity = await self.client.get_input_entity(entity)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 437, in get_input_entity
    await self._get_entity_from_string(peer))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 574, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "my private chat link"

**Comment by AngelSecurityTeam** [comment]
tg://join?invite=XXXXXXXXXXXXXX

**Comment by Markowde3jani** [comment]
> tg://join?invite=XXXXXXXXXXXXXX

same problem
